### ISSUE TITLE
utils/nfs-ls.py is hanging

### ISSUE THREAD

**Issue by jbd** [sahlberg/libnfs-python#36]
Hello,

If I run `nfs-ls` from libnfs using my user, I've got this expected result (secure mount):
```
$ nfs-ls nfs://127.0.0.1/usr
Failed to mount nfs share : mount_cb: RPC error: Mount failed with error MNT3ERR_ACCES(13) Permission denied(13)
```
It is working as root.

If I try `nfs-ls.py`, it is working as root, but it hangs with an unprivileged user:
```
$ python utils/nfs-ls.py nfs://127.0.0.1/usr
nfs <libnfs.NFS object at 0x7feeb93da040>
```
It hangs here. Here is the traceback after hitting ctrl-c:
```
nfs <libnfs.NFS object at 0x7feeb93da040>
^CTraceback (most recent call last):
  File "utils/nfs-ls.py", line 31, in <module>
    ls(sys.argv[1])
  File "utils/nfs-ls.py", line 21, in ls
    for ent in nfs.listdir("."):
  File "/home/jbdenis/Code/libnfs-python/env/lib/python3.8/site-packages/libnfs/__init__.py", line 223, in listdir
    ret = nfs_opendir(self._nfs, path, d)
  File "/home/jbdenis/Code/libnfs-python/env/lib/python3.8/site-packages/libnfs/libnfs.py", line 327, in nfs_opendir
    return _libnfs.nfs_opendir(nfs, path, nfsdir)
KeyboardInterrupt
```
Is that working as expected or should it be considered as a bug ?

Thank you !

**Comment by jbd** [comment]
I don't know if it is an ideal behavior, but it fails early and explicitly: https://github.com/sahlberg/libnfs-python/pull/37
